@startuml
'https://plantuml.com/class-diagram

package model {
    class Player {
        - playersName: String
        - playersLifePoints: Health
        - playersCredits: Credits

        + Player(String playersName)
        + validateName(String name): void
        + getPlayerLifePoints(): Health
        + getPlayerCredits(): Credits
        + getsDamage(int damage): void
        + chargeCredits(Credit credits): void
        + getsCredit(Credit credits): void
    }
}

@enduml