@startuml
'https://plantuml.com/class-diagram

package model {
    class Player {
        - playersName: String
        - playersLifePoints: Health
        - playersCredits: Credits

        + Player(String playersName)
        + validateName(String name): void
        + getPlayerCredits(): Credits
        + getsDamage(Damage damage): void
        + chargeCredits(Credit credits): void
        + substractCredit(Credit credits): void
        + buildsADefense(Tower tower): void
        + canBuy(int value): boolean
        + isAlive(): boolean
    }
}

@enduml