@startuml
'https://plantuml.com/class-diagram

package model {
    class Player {
      - playersName: String
      - playersLifePoints: Health
      - playersCredits: Credit
      + Player(playersName: String)
      + getPlayerCredits(): Credit
      + getsDamage(damage: Damage): void
      + chargeCredits(credits: Credit): void
      + subtractCredits(credits: Credit): void
      + buildsADefense(defense: Defense): void
      + isAlive(): boolean
      + playerInfo(): String
      + hasFunds(): boolean
      + playersBalance(): int
      + resetStats(): Player
    }
}

@enduml