@startuml
'https://plantuml.com/class-diagram

package model {
    class Credit {
      - quantity: int
      + Credit(cant: int)
      + Credit()
      + chargeCredits(creditLoad: Credit): void
      + getQuantity(): int
      + equalTo(credit: Credit): boolean
      + subtractCredits(credit: Credit): void
      + areNegative(): boolean
      + arePositive(): boolean
    }
}

@enduml