@startuml
'https://plantuml.com/class-diagram

package model {
    class Dirt {
      - enemyArrayList: ArrayList<Enemy>
      + Dirt()
      + setEnemy(enemyList: ArrayList<Enemy>): void
      + show(): String
      + enemiesInPlot(): ArrayList<Enemy>
      + addEnemyToPath(newEnemy: Enemy): void
      + setDefense(defense: Defense): void
      + removeDefense(defense: Defense): void
    }
}

@enduml