@startuml
'https://plantuml.com/class-diagram
'TODO: GambeBoard has ArrayList<Point> and ArrayList<Plot> all private
package model {
class GameBoard {
    - plots: Plot[][]
    - enemyPath: ArrayList<Point>
    + start: Point
    + finishLine: Point
    + GameBoard(expectedPlots: Plot[][])
    + availableForBuilding(coordinates: Point): boolean
    + buildDefense(defense: Defense): void
    + getEnemies(): ArrayList<Enemy>
    + getNextPath(plotCoords: Point): Point
    + spawnEnemy(enemyArrayList: ArrayList<Enemy>): void
    + constructPath(): ArrayList<Point>
    + setFinishLine(point: Point): void
    + getFinishLine(): Point
    + getStart(): Point
    + setStart(point: Point): void
    + printMap(): void
    + moveEnemies(): void
    + getPlot(x: int, y: int): Plot
    + isEnemyPath(expectedEnemyPathCoordinates: Point): boolean
    + isStart(point: Point): boolean
    + isFinish(point: Point): boolean
    + getEnemiesInThelastPath(): ArrayList<Enemy>
    + destroyDefense(defenses: ArrayList<Defense>, owl: Enemy): void
    + removeDefense(defense: Defense): void
    + height(): long
    + width(): long
    + getEnemyPath(): ArrayList<Point>
}
}

@enduml