@startuml
'https://plantuml.com/class-diagram

package model {
    class Path {
        + Path()
        + setEnemy(Enemy enemy): void
        + addEnemyToPath(Enemy newEnemy): void
        + display(): String
        + enemiesInPlot(): ArrayList<Enemy>
    }
}

@enduml