@startuml
'https://plantuml.com/class-diagram

!include Plot.puml
!include PlotAvailability.puml
!include NotPlotAvailability.puml
!include Occupied.puml
!include Available.puml
!include Dirt.puml
!include Path.puml
!include Stone.puml

Stone --|> Plot
Dirt --|> Plot
Path --|> Plot
Plot --> PlotAvailability

'left to right direction
skinparam packageStyle rect
PlotAvailability -.> Available
PlotAvailability -.> Occupied
PlotAvailability -.> NotPlotAvailability

@enduml