@startuml
'https://plantuml.com/class-diagram
package model {
abstract class Plot {
  - defense: Defense
  - enemy: Enemy
  - state: PlotAvailability
  + readyToBuild(): boolean
  + setDefense(defense: Defense): void
  + setEnemy(enemyList: ArrayList<Enemy>): void
  + show(): String
  + addEnemyToPath(newEnemy: Enemy): void
  + enemiesInPlot(): ArrayList<Enemy>
  + getDefense(): Defense
  + removeDefense(defense: Defense): void
}
}

@enduml