@startuml
'https://plantuml.com/class-diagram
package model {
    abstract class Plot {
        + readyToBuild(): boolean
        + setDefense(Tower tower): void
        + setEnemy(ArrayList<Enemy> enemyList): void {abstract}
        + addEnemyToPath(Enemy newEnemy) {abstract}
        + enemiesInPlot(): ArrayList<Enemy> {abstract}
        + display(): String {abstract}
        + getDefense(): Tower
    }
}

@enduml