@startuml
'https://plantuml.com/class-diagram
skinparam linetype ortho
!include Plot.puml
!include ../enemy/Enemy.puml
!include ../defense/defense.puml

Plot --> "0..*" Enemy
Plot --> "0..1" Defense

@enduml