@startuml
'https://plantuml.com/class-diagram

package model {
    class Stone {
        + Stone()
        + setEnemy(ArrayList<Enemy> enemyList): void
        + enemiesInPlot(): AttayList<Enemy>
        + show(): String
    }
}

@enduml