@startuml
'https://plantuml.com/class-diagram

package model {
    class HypotenuseMove {
        + HypotenuseMove(int speed)
        + execute(long x, long y, Plot[][] plots, ArrayList<Point> enemyPath): Point
    }
}

@enduml