@startuml
'https://plantuml.com/class-diagram

package model {
    class AlgoDefense {
      - state: GameState
      - player: Player
      - gameboard: GameBoard
      - turn: Turn
      - enemyStrategy: Dictionary
      - antFactory: EnemyFactory
      - spiderFactory: EnemyFactory
      - moleFactory: EnemyFactory
      - owlFactory: EnemyFactory
      - defenses: ArrayList<Defense>
      + AlgoDefense()
      + AlgoDefense(aPlayer: Player)
      + reset(aPlayer: Player): void
      + nextTurn(): void
      + executeTurn(): void
      + buildsADefense(defense: Defense): void
      + spawnAnEnemy(enemyArrayList: ArrayList<Enemy>): void
      + isOccupyByADefense(coordenatesToDirt: Point): boolean
      + damageThePlayer(): void
      + setPlayer(player: Player): void
      + loadEnemies(): void
      + getGameboard(): GameBoard
      + getPlayerInfo(): String
      + gameOver(): boolean
      + getPlayer(): Player
      + getCurrentTurn(): String
    }
}

@enduml