@startuml
'https://plantuml.com/class-diagram
package model {
    class Ant {
        + Ant(Damage damage, Health health, Credit credit, Move movement)
        + generateCredits(): Credit
        + show(): String
        + destroyTower(ArrayList<Defense> defenses): Defense
    }
}
@enduml