@startuml
'https://plantuml.com/class-diagram
package model {
    class Ant {
        + Ant(damage: Damage, health: Health, credit: Credit, movement: Move)
        + generateCredits(): Credit
        + show(): String
        + destroyTower(defenses: ArrayList<Defense>): Defense
    }
}
@enduml