@startuml
'https://plantuml.com/class-diagram

!include Enemy.puml
!include ../damage/Damage.puml
!include ../health/Health.puml
!include ../credit/Credit.puml
!include ../speed/Move.puml

Enemy *-> Credit
Damage <-* Enemy
Move <--* Enemy
Enemy *-->Health

@enduml