@startuml
'https://plantuml.com/class-diagram

!include Enemy.puml
!include Ant.puml
!include Spider.puml
!include EnemyFactory.puml
!include ../health/Health.puml
!include ../damage/Damage.puml

EnemyFactory --> Enemy
Health <- Enemy
Enemy ->Damage
Enemy <|-- Ant
Enemy <|-- Spider

@enduml