@startuml
'https://plantuml.com/class-diagram

package model {
    abstract class Enemy {
        - Speed: int

        + Enemy(int speed, Damage damage, int healthPoints)
        + takeDamage(int amount): void
        + getAward(): int {abstract}
        + enemyDied(): bool
        + generateCredits(): int {abstract}
        + show(): String
    }
}


@enduml