@startuml
'https://plantuml.com/class-diagram
!include Enemy.puml
package model {
    class Owl extends Enemy {
        - healthToChangeMovement: Health

        + Owl(Damage damage, Health health, Credit credit, Move movement, Health healthToChangeMovement)
        + generateCredits(): Credit
        + show(): String
        + takeDamage(Damage damageReceived): void
        + destroyTower(ArrayList<Defense> defenses): Defense
    }
}

@enduml