@startuml
'https://plantuml.com/class-diagram

package model {
    class Spider {
        - CREDITS_MIN_RANGE: int
        - CREDITS_MAX_RANGE: int

        + Spider(int speed, Damage damage, int healthPoints)
        + generateCredits(): Credit
        + show(): String
    }
}

@enduml