@startuml
'https://plantuml.com/class-diagram

package model {
    class Spider {
        - CREDITS_MIN_RANGE: int
        - CREDITS_MAX_RANGE: int
        + generateCredits(): Credit
        + Spider(Damage damage, Health health, Credit credit, Move movement)
        + show(): String
        + destroyTower(ArrayList<Defense> defenses): Defense
    }
}

@enduml