@startuml
'https://plantuml.com/class-diagram


package model {
    class EnemiesParser {
        + getArray(): JSONArray
        + parserFile(): Dictionary
        - loadEnemies(int antAmount, int spiderAmount): ArrayList<Enemy>
    }
}

@enduml