@startuml
'https://plantuml.com/class-diagram

package model {
    class MapParser {
    - plots: Plot[][]
    - fileName: String
    - fileRelativeSource: String
    + MapParser(String file)
    + getObject(): JSONObject
    + initializeMap(): GameBoard
    }
}

@enduml