@startuml
'https://plantuml.com/class-diagram
package model {
    class ConstructionState {
        - remainingConstructionTurns: int
        + ConstructionState(int defenseConstructionTurns)
        + attack(Defense defense, ArrayList<Enemy> enemies): void
    }
}

@enduml