@startuml
'https://plantuml.com/class-diagram

!include Tower.puml
!include WhiteTower.puml
!include SilverTower.puml
!include TowerFactory.puml
!include State.puml
!include ConstructionState.puml
!include OperationalState.puml

OperationalState -.> State
State <.- ConstructionState
TowerFactory --> Tower
Tower -> State
Tower <|-- WhiteTower
Tower <|-- SilverTower

@enduml