@startuml
'https://plantuml.com/class-diagram

!include Defense.puml
!include ../credit/Credit.puml
!include State.puml
!include ../attack/Attack.puml
Attack <--* Defense
Defense *--> State
Credit <- Defense

@enduml