@startuml
'https://plantuml.com/class-diagram

!include TowerFactory.puml
!include Tower_class_diagram.puml
!include State_class_diagram.puml

TowerFactory -> Tower
Tower --> State
top to bottom direction
@enduml