@startuml
'https://plantuml.com/class-diagram
!include State.puml
package model {
    class DestructedState extends State {
        + attack(Defense defense, ArrayList< Enemy > enemies): void
    }
}

@enduml