@startuml
'https://plantuml.com/class-diagram
!include State.puml
package model {
    class OperationalState extends State{
        + attack(Tower tower, Enemy enemy, boolean isOnRange): void
    }
}

@enduml