@startuml
'https://plantuml.com/class-diagram

package model {
    class Range {
        - distance: int
        + Range(int range)
        + isInRange(Defense defense, Enemy enemy): boolean
        + plotsInRange(Point originPoint): ArrayList<Point>
    }
}

@enduml