@startuml
'https://plantuml.com/class-diagram
!include Tower.puml
package model{
    class SilverTower extends Tower{
        + SilverTower(Credit credit, Range rangeAttack, Damage damage, int constructionTurns, Point coordinatesTower)
        + show(): String
    }
}

@enduml