@startuml
'https://plantuml.com/class-diagram
!include State.puml
package model{
    class TemporallyState extends State {
        - TurnAlive: int
        - attack: Attack
        + TemporallyState(Attack newAttack, int operativeTurns)
        + attack(Defense defense, ArrayList<Enemy> enemies): void
    }
}

@enduml