@startuml
'https://plantuml.com/class-diagram
!include Tower.puml

package model {
    class WhiteTower extends Tower{
        + WhiteTower(Credit credit, Range rangeAttack, Damage damage, int constructionTurns, Point cordinatesTower)
        + show(): String
    }
}

@enduml