@startuml
'https://plantuml.com/class-diagram
!include Tower.puml

package model {
    class WhiteTower {
        + WhiteTower(Credit credit, int rangeAttack, Damage damage, int constructionTurns, Points coordinatesTower)
    }
}

WhiteTower --|> Tower

@enduml