@startuml
'https://plantuml.com/class-diagram
!include Tower.puml

package model {
    class WhiteTower {
        + WhiteTower(Credit credit, int rangeAttack, int damage, int cont)
    }
}

WhiteTower --|> Tower

@enduml